const PDFDocument = require('pdfkit');
const reportService = require('./reportServices');

// Generate PDF for all emergency reports
exports.generateEmergencyReportsPDF = async () => {
  return new Promise(async (resolve, reject) => {
    try {
      // Get all reports from database
      const reports = await reportService.getAllReports();
      
      // Create a new PDF document
      const doc = new PDFDocument({
        size: 'A4',
        margin: 50
      });

      // Buffer to store PDF data
      const buffers = [];
      
      // Collect PDF data
      doc.on('data', buffers.push.bind(buffers));
      doc.on('end', () => {
        const pdfData = Buffer.concat(buffers);
        resolve(pdfData);
      });

      // Add header
      doc.fontSize(20)
         .font('Helvetica-Bold')
         .text('Emergency Reports Summary', { align: 'center' })
         .moveDown();

      // Add generation date
      doc.fontSize(12)
         .font('Helvetica')
         .text(`Generated on: ${new Date().toLocaleDateString()} at ${new Date().toLocaleTimeString()}`, { align: 'right' })
         .moveDown();

      // Add summary statistics
      const totalReports = reports.length;
      const highPriorityReports = reports.filter(r => r.priority === 'HIGH').length;
      const mediumPriorityReports = reports.filter(r => r.priority === 'MEDIUM').length;
      const lowPriorityReports = reports.filter(r => r.priority === 'LOW').length;

      doc.fontSize(14)
         .font('Helvetica-Bold')
         .text('Summary Statistics:', { align: 'left' })
         .moveDown(0.5);

      doc.fontSize(11)
         .font('Helvetica')
         .text(`Total Reports: ${totalReports}`)
         .text(`High Priority: ${highPriorityReports}`)
         .text(`Medium Priority: ${mediumPriorityReports}`)
         .text(`Low Priority: ${lowPriorityReports}`)
         .moveDown(1);

      // Add line separator
      doc.moveTo(50, doc.y)
         .lineTo(545, doc.y)
         .stroke()
         .moveDown();

      // Add reports section header
      doc.fontSize(16)
         .font('Helvetica-Bold')
         .text('Detailed Reports', { align: 'left' })
         .moveDown();

      // Add each report
      reports.forEach((report, index) => {
        // Check if we need a new page
        if (doc.y > 700) {
          doc.addPage();
        }

        // Report card background
        const cardY = doc.y;
        doc.rect(50, cardY, 495, 150)
           .fillAndStroke('#f8f9fa', '#dee2e6');

        // Reset position for text
        doc.y = cardY + 10;

        // Report header
        doc.fontSize(12)
           .font('Helvetica-Bold')
           .fillColor('#000')
           .text(`Report #${index + 1}`, 60, doc.y);

        // Priority badge
        const priorityColor = report.priority === 'HIGH' ? '#dc3545' : 
                             report.priority === 'MEDIUM' ? '#fd7e14' : '#28a745';
        
        doc.rect(450, doc.y - 2, 50, 16)
           .fill(priorityColor);
        
        doc.fontSize(10)
           .font('Helvetica-Bold')
           .fillColor('#fff')
           .text(report.priority, 455, doc.y, { width: 40, align: 'center' });

        doc.fillColor('#000').moveDown(0.8);

        // Report details
        doc.fontSize(11)
           .font('Helvetica-Bold')
           .text(`Title: `, 60, doc.y, { continued: true })
           .font('Helvetica')
           .text(report.title);

        doc.font('Helvetica-Bold')
           .text(`Description: `, 60, doc.y, { continued: true })
           .font('Helvetica')
           .text(report.description, { width: 480, align: 'justify' });

        doc.font('Helvetica-Bold')
           .text(`Location: `, 60, doc.y, { continued: true })
           .font('Helvetica')
           .text(`Lat: ${report.latitude}, Long: ${report.longitude}`);

        doc.font('Helvetica-Bold')
           .text(`Time: `, 60, doc.y, { continued: true })
           .font('Helvetica')
           .text(report.time);

        doc.font('Helvetica-Bold')
           .text(`Resolved At: `, 60, doc.y, { continued: true })
           .font('Helvetica')
           .text(report.resolvedAt);

        doc.font('Helvetica-Bold')
           .text(`Created: `, 60, doc.y, { continued: true })
           .font('Helvetica')
           .text(new Date(report.createdAt).toLocaleDateString());

        // Move to next report
        doc.y = cardY + 160;
      });

      // Add footer
      doc.fontSize(8)
         .fillColor('#666')
         .text('Generated by NeighborHub Emergency Report System', 50, doc.page.height - 50, {
           align: 'center',
           width: 495
         });

      // Finalize the PDF
      doc.end();

    } catch (error) {
      reject(error);
    }
  });
};

// Generate PDF for a specific emergency report
exports.generateSingleReportPDF = async (reportId) => {
  return new Promise(async (resolve, reject) => {
    try {
      // Get specific report from database
      const report = await reportService.getReportById(reportId);
      
      if (!report) {
        reject(new Error('Report not found'));
        return;
      }

      // Create a new PDF document
      const doc = new PDFDocument({
        size: 'A4',
        margin: 50
      });

      // Buffer to store PDF data
      const buffers = [];
      
      // Collect PDF data
      doc.on('data', buffers.push.bind(buffers));
      doc.on('end', () => {
        const pdfData = Buffer.concat(buffers);
        resolve(pdfData);
      });

      // Add header
      doc.fontSize(20)
         .font('Helvetica-Bold')
         .text('Emergency Report Details', { align: 'center' })
         .moveDown();

      // Add generation date
      doc.fontSize(12)
         .font('Helvetica')
         .text(`Generated on: ${new Date().toLocaleDateString()} at ${new Date().toLocaleTimeString()}`, { align: 'right' })
         .moveDown(2);

      // Priority badge
      const priorityColor = report.priority === 'HIGH' ? '#dc3545' : 
                           report.priority === 'MEDIUM' ? '#fd7e14' : '#28a745';
      
      doc.rect(50, doc.y, 100, 30)
         .fill(priorityColor);
      
      doc.fontSize(14)
         .font('Helvetica-Bold')
         .fillColor('#fff')
         .text(`${report.priority} PRIORITY`, 55, doc.y + 8, { width: 90, align: 'center' });

      doc.fillColor('#000').moveDown(3);

      // Report details
      doc.fontSize(16)
         .font('Helvetica-Bold')
         .text('Report Information', { underline: true })
         .moveDown();

      // Create a detailed view
      const details = [
        { label: 'Report ID', value: report.id },
        { label: 'Title', value: report.title },
        { label: 'Description', value: report.description },
        { label: 'Location (Latitude)', value: report.latitude.toString() },
        { label: 'Location (Longitude)', value: report.longitude.toString() },
        { label: 'Time Reported', value: report.time },
        { label: 'Resolved At', value: report.resolvedAt },
        { label: 'Created Date', value: new Date(report.createdAt).toLocaleDateString() },
        { label: 'Last Updated', value: new Date(report.updatedAt).toLocaleDateString() }
      ];

      details.forEach(detail => {
        doc.fontSize(12)
           .font('Helvetica-Bold')
           .text(`${detail.label}: `, 50, doc.y, { continued: true })
           .font('Helvetica')
           .text(detail.value, { width: 450 })
           .moveDown(0.5);
      });

      // Add footer
      doc.fontSize(8)
         .fillColor('#666')
         .text('Generated by NeighborHub Emergency Report System', 50, doc.page.height - 50, {
           align: 'center',
           width: 495
         });

      // Finalize the PDF
      doc.end();

    } catch (error) {
      reject(error);
    }
  });
};
